# fly.toml file generated for amazing on 2023-04-09T20:46:55+02:00

app = "amazing"
kill_signal = "SIGTERM"
primary_region = "ams"

[deploy]
release_command = "/app/bin/migrate"

[env]
PHX_SERVER = "true"
PHX_HOST = "amazing.fly.dev"
PORT = "8080"

[metrics]
path = "/metrics"
port = 9568

[[services]]
internal_port = 8080
processes = ["app"]
protocol = "tcp"

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[[services]]
internal_port = 2342
processes = ["app"]
protocol = "tcp"

[[services.ports]]
port = 2342
